config/routes.rb
Gerse::Application.routes.draw do
  resources :parent_pages

  resources :child_pages

  resources :archives

  devise_for :users
  resources :posts

  root 'posts#index'

end

app/models/child_page.rb
class ChildPage < ActiveRecord::Base
  belongs_to :parent_page
end

app/controllers/child_pages_controller.rb
class ChildPagesController < ApplicationController
  before_action :set_child_page, only: [:show, :edit, :update, :destroy]

  # GET /child_pages
  # GET /child_pages.json
  def index
    @child_pages = ChildPage.all
  end

  # GET /child_pages/1
  # GET /child_pages/1.json
  def show
  end

  # GET /child_pages/new
  def new
    @child_page = ChildPage.new
  end

  # GET /child_pages/1/edit
  def edit
  end

  # POST /child_pages
  # POST /child_pages.json
  def create
    @child_page = ChildPage.new(child_page_params)

    respond_to do |format|
      if @child_page.save
        format.html { redirect_to @child_page, notice: 'Aloldal sikeresen létrehozva.' }
        format.json { render action: 'show', status: :created, location: @child_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @child_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /child_pages/1
  # PATCH/PUT /child_pages/1.json
  def update
    respond_to do |format|
      if @child_page.update(child_page_params)
        format.html { redirect_to @child_page, notice: 'Aloldal sikeresen frissítve.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @child_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /child_pages/1
  # DELETE /child_pages/1.json
  def destroy
    @child_page.destroy
    respond_to do |format|
      format.html { redirect_to child_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child_page
      @child_page = ChildPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_page_params
      params.require(:child_page).permit(:title, :body, :parent_page_id)
    end
end

app/helpers/child_pages_helper.rb
module ChildPagesHelper
end

app/views/child_pages/_form.html.haml
= simple_form_for @child_page do |f|
  = f.input :title, label: "Név"   
  = f.input :body, label: "Test", :input_html => { :rows => 20, :style => 'height: auto'}
  = f.input :parent_page_id, :collection => ParentPage.all, :value_method => :id,:label => "Szülő oldal" ,:include_blank => false
  = f.submit "Mentés" , class: "button"
  = link_to "Mégse", child_pages_path, class: "button secondary"

app/views/child_pages/edit.html.haml
%h1 Aloldal szerkeszétse

= render 'form'

app/views/child_pages/index.html.haml
%h1 Aloldalak

%table
  %tr
    %th Cím
    %th Szülő oldal
    %th
    %th
    %th

  - @child_pages.each do |child_page|
    %tr
      %td= link_to child_page.title, child_page
      %td= ParentPage.find(child_page.parent_page_id).title if child_page.parent_page
      %td= link_to 'Szerkesztés', edit_child_page_path(child_page)
      %td= link_to 'Törlés', child_page, :method => :delete, :data => { :confirm => 'Biztos, hogy törlöd?' }

%br

= link_to 'Új aloldal', new_child_page_path, class: "button"

app/views/child_pages/new.html.haml
%h1 Új aloldal

= render 'form'

app/views/child_pages/show.html.haml
.row
  .small-12.columns
    .row
      .small-12.columns
        %h1= @child_page.title
    .row
      .small-12.columns
        = simple_format(@child_page.body)