config/routes.rb
Gerse::Application.routes.draw do
  resources :parent_pages

  resources :child_pages

  resources :archives

  devise_for :users
  resources :posts

  root 'posts#index'

end

app/views/layouts/_admin_nav.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
.contain-to-grid
  %nav.top-bar{"data-topbar" => ""}
    %ul.title-area
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      / Right Nav Section
      /%ul.right
      /  %li.has-dropdown
      /    %a{href: "#"} Településünk
      /    %ul.dropdown
      /      %li
      /        %a{href: "#"} Proba
      /  %li
      /    %a{href: "#"} Archívum
      /  %li
      /    %a{href: "#"} Vendégváró
      / Left Nav Section
      %ul.left
        /%li{class: "#{"active" if controller.controller_name != "post"}"}
        %li.has-dropdown
          %a{href: "#"} Hírek
          %ul.dropdown
            %li
              = link_to 'Új Hír', new_post_path
        %li.has-dropdown
          %a{href: "#"} Archívum
          %ul.dropdown
            %li
              = link_to 'Új Archívum', new_archive_path
        %li
          = link_to "Szülő oldalak", parent_pages_path
        %li
          = link_to "Aloldalak", child_pages_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
.contain-to-grid
  %nav.top-bar{"data-topbar" => ""}
    %ul.title-area
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      / Right Nav Section
      %ul.right
        - ParentPage.all.each do |ppage|
          %li.has-dropdown
            %a{href: "#"}= ppage.title
            %ul.dropdown
              - ppage.child_pages.each do |cpage|
                %li
                  = link_to cpage.title, cpage

        /%li.has-dropdown
        /  %a{href: "#"} Településünk
        /  %ul.dropdown
        /    %li
        /      %a{href: "#"} Proba
        %li{class: "#{"active" if controller.controller_name == "archives"}"}
          = link_to "Archívum", archives_path
        %li
          %a{href: "#"} Vendégváró
      / Left Nav Section
      %ul.left
        %li{class: "#{"active" if controller.controller_name == "posts"}"}
          = link_to "Aktuális", root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Gersekarát'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Gerse'}"}
    = stylesheet_link_tag "application"
    -# Foundation 5 won't work with Rails Turbolinks
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .navigation
      %header
        - if can? :update, @post
          = render 'layouts/admin_nav'
        = render 'shared/logo'
        = render 'layouts/navigation'
    .row
      %main{:role => "main"}
        = render 'layouts/messages'
        = yield
    = render 'shared/footer'
    -# Foundation 5 won't work when application.js is included in HEAD
    = javascript_include_tag "application"